[project]
name = "ropacea"
version = "0.0.1"
dependencies = [
    'pandas'
]
description = "Risk-Optimized Portfolios: An Analysis of Covariance Estimation Approaches"


[tool.setuptools]
packages = ["ropacea"]